name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Congratulations! You are making your first issue to art, Thanks.'
        pr-message: 'Congratulations! You are making your first Pull request to art, Thanks.'
